export enum UserLogAction {
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  EMAIL_CHANGE_REQUEST = 'EMAIL_CHANGE_REQUEST',
  EMAIL_CHANGE_APPROVED = 'EMAIL_CHANGE_APPROVED',
  EMAIL_CHANGE_REVOKED = 'EMAIL_CHANGE_REVOKED',
  EMAIL_CHANGE_RECOVERED = 'EMAIL_CHANGE_RECOVERED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  ACCOUNT_LOCK = 'ACCOUNT_LOCK',
  ACCOUNT_UNLOCK = 'ACCOUNT_UNLOCK',
  SECURITY_ALERT = 'SECURITY_ALERT',
}